DebtManager.Web/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DebtManager.Core.Entities;
using DebtManager.Core.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DebtManager.Web.Controllers
{
    public class ContactController : Controller
    {
        private readonly IAsyncRepository<Contact> _contactRepository;


        public ContactController(IAsyncRepository<Contact> repository)
        {
            _contactRepository = repository;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var contactList = await _contactRepository.ListAllAsync();
            if (contactList.Count == 0)
            {
                var contact = new Contact();
                contact.Name = "Kamrul Hasan";
                contact.Phone = "01722329228";
                contact.Email = "khasancsit@gmail.com";
                contact.Address = "Dhaka, Bangladesh";
                contact.Status = true;
                contact.CreateAt = DateTime.Now;
                contact.UpdateAt = DateTime.Now;
                await _contactRepository.AddAsync(contact);
            }

            return View(contactList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Name,Phone,Email,Address,CreateAt,UpdateAt,Status")] Contact contact)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _contactRepository.AddAsync(contact);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction(nameof(Create));
                }
            }
            catch (Exception)
            {
                return View();
            }
        }

        [HttpGet, ActionName("Edit")]
        public async Task<IActionResult> Edit(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction(nameof(Index));
            }

            var contactToUpdate = await _contactRepository.GetByIdAsync(id);
            if (contactToUpdate == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(contactToUpdate);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Contact contact)
        {
            try
            {
                if (id == contact.Id)
                {
                    contact.UpdateAt = DateTime.Now;
                    await _contactRepository.UpdateAsync(contact);
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return View();
            }
        }



        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }

            var contact = await _contactRepository.GetByIdAsync(id);

            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // Delete/Contact/5
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction(nameof(Index));
            }

            var contact = await _contactRepository.GetByIdAsync(id);
            if (contact == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(contact);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Contact contact)
        {
            try
            {
                if (id == contact.Id)
                {
                    await _contactRepository.DeleteAsync(contact);
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return View();
            }
        }



    }
}

DebtManager.Web/Controllers/MyDebitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DebtManager.Core.Entities;
using DebtManager.Core.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DebtManager.Web.Controllers
{
    public class MyDebitController : Controller
    {

        private readonly IAsyncRepository<MyDebit> _myDebitRepository;
        private readonly IAsyncRepository<Contact> _myContactRepository;

        public MyDebitController(IAsyncRepository<MyDebit> repository, IAsyncRepository<Contact> contactRepository)
        {
            _myDebitRepository = repository;
            _myContactRepository = contactRepository;
        }

        // GET: MyDebt
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            //var myDebitList = await _myDebitRepository.ListAllAsync();

            var myDebitList = _myDebitRepository.group
            return View(myDebitList);
        }

        // GET: MyDebt/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction(nameof(Index));
            }
            var myDebtDetail = await _myDebitRepository.GetByIdAsync(id);
            if (myDebtDetail == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(myDebtDetail);
        }

        // GET: MyDebt/Create
        public async Task<IActionResult> Create()
        {
            var contactList = await _myContactRepository.ListAllAsync();
            SelectList list = new SelectList(contactList, "Id", "Name");
            ViewBag.debtId = list;
            return View();
        }

        // POST: MyDebt/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MyDebit myDebt)
        {
            if (myDebt == null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                myDebt.CreateAt = DateTime.Now;
                myDebt.UpdateAt = DateTime.Now;
                myDebt.Status = true;
                await _myDebitRepository.AddAsync(myDebt);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MyDebt/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction(nameof(Index));
            }

            var myDebit = await _myDebitRepository.GetByIdAsync(id);
            if (myDebit == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(myDebit);
        }

        // POST: MyDebt/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, MyDebit mydebit)
        {
            if (id != mydebit.Id)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                await _myDebitRepository.UpdateAsync(mydebit);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MyDebt/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction(nameof(Index));
            }

            var deleteItem = await _myDebitRepository.GetByIdAsync(id);
            if (deleteItem == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(deleteItem);
        }

        // POST: MyDebt/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, MyDebit myDebit)
        {
            if (id != myDebit.Id)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                await _myDebitRepository.DeleteAsync(myDebit);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DebtManager.Web/Controllers/TheirDebitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DebtManager.Core.Entities;
using DebtManager.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DebtManager.Web.Controllers
{
    public class TheirDebitController : Controller
    {
        private readonly IAsyncRepository<TheirDebt> _theirDebitRepository;
        private readonly IAsyncRepository<Contact> _myContactDebitRepository;


        public TheirDebitController(IAsyncRepository<TheirDebt> repository, IAsyncRepository<Contact> contactRepository)
        {
            _theirDebitRepository = repository;
            _myContactDebitRepository = contactRepository;
        }


        public async Task<IActionResult> Index()
        {
            var theirDebit = await _theirDebitRepository.ListAllAsync();
            return View(theirDebit);
        }

        // GET: TheirDebit/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction(nameof(Index));
            }

            var theirDebit = await _theirDebitRepository.GetByIdAsync(id);
            if (theirDebit == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(theirDebit);
        }


        // GET: CREATE 
        public async Task<IActionResult> Create()
        {
            var contactList = await _myContactDebitRepository.ListAllAsync();
            SelectList list = new SelectList(contactList, "Id", "Name");
            ViewBag.debtId = list;
            return View();
        }


        // POST: THEIR DEBIT/CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TheirDebt theirDebt)
        {
            if (theirDebt == null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                await _theirDebitRepository.AddAsync(theirDebt);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // GET: THEIR DEBIT/EDIT
        public async Task<IActionResult> Edit(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction(nameof(Index));
            }

            var theirDebit = await _theirDebitRepository.GetByIdAsync(id);
            if (theirDebit == null)
            {
                return RedirectToAction(nameof(id));
            }

            return View(theirDebit);
        }


        // POST: TheirDebit/EDIT
        public async Task<IActionResult> Edit(int id, TheirDebt theirDebt)
        {
            if (id != theirDebt.Id)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                await _theirDebitRepository.UpdateAsync(theirDebt);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return View();
            }
        }

        //GET: TheirDebit/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0)
            {
                return RedirectToAction(nameof(Index));
            }

            var deleteItem = await _theirDebitRepository.GetByIdAsync(id);
            if (deleteItem == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(deleteItem);
        }


        //POST: TheirDebit/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, TheirDebt theirDebt)
        {
            if (id != theirDebt.Id)
            {
                return RedirectToAction(nameof(Index));
            }

            await _theirDebitRepository.DeleteAsync(theirDebt);
            return RedirectToAction(nameof(Index));
        }

    }
}

DebtManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Debt Manager</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/mdb.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark primary-color">

        <!-- Navbar brand -->
        <a class="navbar-brand"  asp-controller="Home" asp-action="index">Debit Manager</a>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Home" asp-action="index">
                        <i class="fas fa-home"></i> Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="MyDebit" asp-action="Index"><i class="fas fa-arrow-circle-down"></i> My Debit</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="TheirDebit" asp-action="Index"><i class="fas fa-arrow-circle-up"></i> Their Debit</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Contact" asp-action="Index"><i class="far fa-address-book"></i> Contact</a>
                </li>
            </ul>
            <!-- Links -->

            <ul class="form-inline navbar-nav ">
                <li class="md-form my-0">
                    <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false"><i class="fas fa-cogs"></i>Setting</a>
                    <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#"><i class="fas fa-user"></i> Profile</a>
                        <a class="dropdown-item" href="#"><i class="fas fa-shield-alt"></i> Security</a>
                        <a class="dropdown-item" href="#"><i class="fas fa-sign-out-alt"></i> Logout</a>
                    </div>
                </li>

                </li>
            </ul>
        </div>
        <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - DebtManager</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/popper.min.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/mdb.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>